improvement: Update node version engine in package settings #155
strapi-community/strapi-provider-upload-google-cloud-storage pull request #159
Opened 2023-01-23 16:23 UTC by jpcmf

2023-01-26 15:01 UTC, Lith requested changes
I suggest to allow all node version between 16 and 18

2023-01-26 15:01 UTC, Lith commented on package.json
> +    "node": ">=16.19.0 <=18.x.x",
```suggestion
    "node": ">=16.x.x <=18.x.x",
```

2023-01-27 00:33 UTC, jpcmf commented
> I suggest to allow all node version between 16 and 18

Sounds good @Lith!

2023-01-30 13:39 UTC, Lith approved these changes

2023-01-30 13:48 UTC, Lith commented
Thanks, sorry about that, but we've missed to Signing your commit, and I can rebase & merge without :( 
You will find more information here : https://docs.github.com/articles/about-gpg/

2023-02-01 15:10 UTC, jpcmf commented
> Thanks, sorry about that, but we've missed to Signing your commit, and I can rebase & merge without :( You will find more information here : https://docs.github.com/articles/about-gpg/

Please @Lith, check if everything is ok now.

2023-02-01 22:36 UTC, JohnGale87 commented on package.json
>      "npm": "8"
Per my comment in the issue:

```suggestion
    "npm": ">=8"
```

2023-02-01 22:36 UTC, JohnGale87 commented on package.json
>      "npm": "8"
https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage/issues/155#issuecomment-1412832543

2023-02-02 07:53 UTC, Lith commented
I will merge manually this PR because of GPG restriction, this merging is blocked from GitHub.

2023-02-07 12:43 UTC, nielsbox commented
> I will merge manually this PR because of GPG restriction, this merging is blocked from GitHub.
Hi @Lith when will you merge this? Really blocking...

2023-02-10 20:44 UTC, closed without merging